### ISSUE TITLE
quetzal-list-box and quetzal-list-combo-box don't expose value and selectedIndex

### ISSUE THREAD

**Issue by warpech** [JanMiksovsky/quetzal#1]
I am just playing around with Quetzal. It is great and very promising!

I would like to use `<quetzal-list-box>` and  `<quetzal-list-combo-box>` in some prototype app I am playing with. I have noticed that I have no way to read value of those boxes.

I think they should expose properties `value` and `selectedIndex` just like an HTML `<select>` element does. 

In my app I just need `selectedIndex` (2 way bindable like `selectedIndex="{{ currentSelection }}"`). I am willing to experiment with writing a pull request about it.

**Comment by warpech** [comment]
I noticed that `<quetzal-list-box>` extends `<polymer-selector>`, which provides exactly what I want using properties `selected` (replacement for selectedIndex) and `selectedItem` (replacement for value), :tada: 

But I cannot get this to work as nice with `<quetzal-list-combo-box>`. It seems that when I trigger `combobox.selected = 2` programatically, the underlying property is changed but the displayed text in `textBox` does not change.

**Comment by JanMiksovsky** [comment]
@warpech Nice to hear from you! Thanks for taking a look at these elements, playing with them, and taking the time to send me your comments.
- Your comments about mirroring the API of a `<select>` element are reasonable. I'll take a look at reproducing the semantics of a `<select>` and, assuming there are no gotchas, we could make the pitch to the Polymer team to adopt those changes at the level of polymer-selector or polymer-select.
- The quetzal-list-combo-box class doesn't derive from polymer-selector, so it doesn't automatically pick up the same semantics. It shouldn't be too hard to add that, however.

Both of these seem eminently doable. I'm just about to head out of town for a week or so. I might be able to squeeze in time to look at this before I go, otherwise it would likely be the second week of September. I'll let you know when I have something worth taking a look at.

**Comment by JanMiksovsky** [comment]
I've checked in (33fa1bb156aa179f107e909a8ef6db70991e96de) a quick shot at giving quetzal-list-combo-box selected and selectedItem properties. These might be enough to unblock you, but I want to work on these more.
- Upon further reflection, I believe the value property for a combo box should reflect the contents of the combo box's text box portion, which may differ from the selected item. One reason combo boxes exist is to permit users to enter text which may not appear as an explicit choice in a list. E.g., in a fixed list of colors, a user may want to enter some color name which doesn't appear in the list. In that case, the combo box's value will reflect the actual text entered, while the selected and selectedIndex properties would indicate no selection had been made from the list. Another reason to keep value separate is that value is always text, while selectedItem is a DOM element.
- Value should be automatically updated when a selection is made (by user or code) from the list, but this doesn't work yet. That is, if you set the selected attribute on the combo box, the selection will change, and the text box content will update, but the combo box's value attribute won't reflect the new text in the text box. Fixing that will take more time than I've got today.
- Another thing I need to fix is to make the selected property a full attribute so that it can be set or read from markup. That's Not Yet Implemented.
- One note: the source for polymer-selector indicates that the selected attribute doesn't necessarily have to be an index. The source for list-box and list-combo-box currently assume that selected is always the same as selectedIndex, but at some point that will need to get fixed. A new selectedIndex property should be introduced (probably at the level of polymer-selection, since it's generally useful).

Anyway, I hope that helps and that you're at least unblocked. (Let me know if not.) I'll pick this up again when I'm back in early September.

**Comment by warpech** [comment]
Archiving this issue and switching to watch https://github.com/elix/elix 🍿 

@JanMiksovsky, I appreciate your commitment to Web Components a lot!

**Comment by JanMiksovsky** [comment]
@warpech Thanks for your kind words. Sorry this bug sat idle for so long!

In an odd bit of timing, I'm just now drafting the second Elix RFC, which specifically proposes how the project should handle single selection. Among other things, the proposal suggests a means by which we'll ensure that all Elix components that support single-selection expose a `selectedIndex` property. :) (We'll tackle how to do `value` later.) You can follow along by watching the [Elix RFC repository](https://github.com/elix/rfcs); the proposal should appear as a pull request in the next week or so. I'll look forward to any comments you can offer.

**Comment by warpech** [comment]
Great, I will watch the RFC repo as well!
